version: "3.7"
services: 
    wordpress:
        image: $DOCKER_REG/yu-wp-instance:latest
        env_file: env.env
        labels: 
            - "oid=$oid" # Label for order id, this will in nginx configuration
            - "plan=$plan" # Taken plan backup 
        ports: 
            - "0:80" # Random Port Choosen by system
        volumes: 
            - wp-content:/var/www/html 
            - wps_data:/wp/link # This mount point to used for backup purposes
        deploy: 
            resources:
                limits:
                    cpus: '0.50'
                    memory: "256M"
            placement:
                constraints:
                    - "node.id==$nid"

volumes: 
    wp-content:
    wps_data:
        external: true
            name: wps_data    
