version: "3.7"
services: 
    wordpress:
        labels:
            - "oid={{.OID}}"
        image: {{.DOCKER_REG}}/yu_wp:wp
        env_file: env.env
        networks:
            - wp_overlay
        ports: 
            - "0:9000" # Random Port Choosen by system
        hostname: "wp-{{.OID}}" # For network lookup    
        volumes: 
        #    - wp-content:/var/www/{{.OID}}/html 
            - wps_data:/var/www # This mount point to used for backup purposes
        deploy: 
            resources:
                limits:
                    cpus: '0.50'
                    memory: "256M"
            placement:
                constraints:
                    - "node.id=={{.NODEID}}"

volumes: 
   # wp-content:
    wps_data:
        external: 
            name: wps_data    

networks:
    wp_overlay:
        external:
            name: wp_overlay
