version: "3.7"
services: 
    backend:
        image: ${DOCKER_REG}/yu_wp:backend
        ports: 
            - "80:80"
        env_file: env/backend.env    
        volumes:
            - log:/var/log    
            - wp:/var/wp
        networks: 
            - wp_overlay
        deploy:
            placement:
                constraints:
                    - "node.id==${DNODEID}"        

volumes:
    log:
    wp:        

networks: 
    wp_overlay:
        external: 
            name: wp_overlay        