version: "3.7"
services:
    db:
        hostname: db
        image: ${DOCKER_REG}/yu_wp:db
        
        env_file: 
            - env/db.env
        volumes: 
            - db-data:/var/lib/mysql
            - log:/var/log 
            - wp-data:/var/wp/db
        deploy:
            placement:
                constraints:
                    - "node.id==${DNODEID}"    
        networks:
            - wp_overlay 
                        
volumes:
    wp-data: 
    db-data:
    log:    

networks:
    wp_overlay:
        external: 
            name: wp_overlay