# Service Definition for nginx servers 
version: "3.7"
services: 
    nginx:
        deploy:
            placement:
              constraints:
                  - "node.id==${DNODEID}"

        environment:
            DNODEID: ${DNODEID}
            NODEID: ${HOSTNAME}
            DOCKER_REG: ${DOCKER_REG}
            
        env_file:
            - env/nginx.env
        networks: 
            - wp_overlay
            
        image: ${DOCKER_REG}/yu_wp:nginx
        volumes: 
            - conf:/etc/nginx
            - logs:/var/log
            - wp:/var/wp
            - /var/run/docker.sock:/var/run/docker.sock  #Docker Related stuff
            - certs:/var/letsencrypt
            - wps_data:/var/wp/html
            - /var/www/html:/var/wp/html
volumes: 
    wp:
    conf:    
    logs: # For logs
    certs:          # For Let'sEncrypt Certificates
    wps_data:
            external:
                    name: wps_data
networks: 
    wp_overlay:
        external: 
            name: wp_overlay            
