version: "3.7"
services: 
    redis:
        image: redis:alpine
        ports: 
            - "6379:6379"
        volumes:    
            - logs:/var/log  #For Loggin purposes 
        deploy:
            placement:
                constraints:
                    - "node.role==manager"   
        networks: 
            - wp_overlay               
volumes:
    logs:            

networks:
    wp_overlay:
        name: wp_overlay