version: "3.7"
services: 
    redis:
        hostname: redis
        image: redis:alpine
        volumes:    
            - logs:/var/log  #For Loggin purposes 
        deploy:
            placement:
                constraints:
                    - "node.role==manager"   
        networks: 
            - wp_overlay               
volumes:
    logs:            

networks:
    wp_overlay:
        external: 
            name: wp_overlay    